### ISSUE TITLE
Issues with next version of ggplot2

### ISSUE THREAD

**Issue by thomasp85** [open-AIMS/bayesnec#102]
Hi

We preparing the next release of ggplot2 and our reverse dependency checks show that your package is failing with the new version. Looking into it we see that this is due to changes in the warnings and errors thrown by ggplot2 that you test for in your package

You can install the release candidate of ggplot2 using `devtools::install_github('tidyverse/ggplot2@v3.4.0-rc')` to test this out.

We plan to submit ggplot2 by the end of October and hope you can have a fix ready before then

Kind regards
Thomas

**Comment by dbarneche** [comment]
Hi Thomas, thanks for your message, and apologies for the long delay to reply. We just installed the version you recommended and could not detect any check issues on both mac and windows. Would you be able to flag where the specific issue might be?

**Comment by thomasp85** [comment]
If you see no issues with the CRAN version of your package and the RC version of ggplot2 it has likely been a false positive on our side and you can safely ignore it.

**Comment by dbarneche** [comment]
Thanks!
