### ISSUE TITLE
test-nsec.R unexpected original code

### ISSUE THREAD

**Issue by dbarneche** [open-AIMS/bayesnec#125]
In [test-nsec.R](https://github.com/open-AIMS/bayesnec/blob/125d04adfa437d9a919130c1e029116ca5fccf8e/tests/testthat/test-nsec.R#L19) it is unclear why

```
  expect_error(nsec(manec_example, ecx_val = 0.9))
  expect_error(nsec(nec4param, ecx_val = 0.9))
```

should be errors. Commented out for now and transformed to `expect_type`.
Can you please review?

**Comment by beckyfisher** [comment]
This test is not relevant, ecx_val is not an argument of nsec. It is an error and should be deleted.
