### ISSUE TITLE
Plots not displaying in the pkgdown website

### ISSUE THREAD

**Issue by padpadpadpad** [open-AIMS/bayesnec#154]
Hi all

You probably know about this already but the plots are not rendering on the website at present.

![Screenshot 2023-12-14 at 08 49 22](https://github.com/open-AIMS/bayesnec/assets/10220722/1d8db73f-9c24-4b17-b45f-7e231768b055)

**Comment by dbarneche** [comment]
Thanks @padpadpadpad , issue has been fixed.
