### ISSUE TITLE
Add wb1.3 model to bayesnec suite

### ISSUE THREAD

**Issue by jovdam** [open-AIMS/bayesnec#40]
[drc.pdf](https://github.com/open-AIMS/bayesnec/files/5670383/drc.pdf)
Formula at p138

**Comment by beckyfisher** [comment]
A range of extra models from the drc package have been added including wb1.2,, wb1.2, LL.3, LL.4, LL.5, BC.4, BC.5.
In addition we added some curved nec hormesis models.
