### ISSUE TITLE
Add number of divergent transitions to summary()-output or $mod_stats

### ISSUE THREAD

**Issue by MNordborg** [open-AIMS/bayesnec#45]
I think it would be quite useful if it was possible to get a summary/overview of the number of divergent transitions for each candidate model, either when using summary() or in the $mod_stats, for use in assessing which candidate models are ok to include or not. Especially if someone (like me for example) are running model fitting for several MANECs overnight (eg both on the binomial and binomial distribution across a couple of data sets) and then doing the assessments the next day.

**Comment by beckyfisher** [comment]
In the revised version these are now returned with summary().
