### ISSUE TITLE
Add a formula method for bnec

### ISSUE THREAD

**Issue by beckyfisher** [open-AIMS/bayesnec#64]
The main function bnec() should (also) get a proper formula method. This
substantially simplifies handling of variable transformations within the
formula, ideally also weights, and finally an na.action would control the
handling of missing values in the standard way. Standard methods like
formula(), terms(), model.frame(), model.matrix(), etc. should work in the
standard way as well.

**Comment by dbarneche** [comment]
`terms()` and `model.matrix()` will not be provided because brms standard formulation is not matrix based, and `brmsfit` objects do not have these methods either.
