### ISSUE TITLE
Default args to amend

### ISSUE THREAD

**Issue by beckyfisher** [open-AIMS/bayesnec#69]
The definition

amend.bayesmanecfit <- function(object, drop, add, loo_controls, x_range =
NA,
                                 precision = 1000, sig_val = 0.01,
                                 priors, pointwise) {
   amend.default(object, drop, add, loo_controls, x_range = NA,
                 precision = 1000, sig_val = 0.01,
                 priors, pointwise)
}

raises the question why the specified x_range, precision and sig_val
arguments when calling amend.bayesmanecfit are not used when calling
amend.default.

**Comment by dbarneche** [comment]
1c70efe closes
